# Generated by Django 5.2.17 on 2026-09-12 02:35

import apps.core.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('tg_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Telegram ID')),
                ('tg_username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Telegram username')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Last name')),
                ('photo', models.ImageField(blank=True, null=True, storage=apps.core.storage.HashedStorage(), upload_to='avatars/', verbose_name='Photo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff status')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'auth_user',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDeliveryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_current', models.BooleanField(default=True, verbose_name='Is current')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full name')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip code')),
                ('address_line', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line')),
                ('destination_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Destination code')),
                ('region_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Region code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_data', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User delivery data',
                'verbose_name_plural': 'User delivery data',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPromocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('used', models.PositiveIntegerField(default=1, verbose_name='Used')),
                ('promocode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.promocode', verbose_name='Promo code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User promocode',
                'verbose_name_plural': 'User promocodes',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSettingsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('preferred_payment_currency', models.CharField(default='usdt', max_length=50, verbose_name='Preferred payment currency')),
                ('preferred_network', models.CharField(default='trc20', max_length=50, verbose_name='Preferred network')),
                ('particles_style', models.CharField(choices=[('none', 'None'), ('lines', 'Lines'), ('shapes', 'Shapes'), ('both', 'Both')], default='both', max_length=50, verbose_name='Particles style')),
                ('default_theme', models.CharField(choices=[('light', 'Light theme'), ('dark', 'Dark theme')], default='light', max_length=50, verbose_name='Default theme')),
                ('custom_theme', models.CharField(blank=True, choices=[('light', 'Light theme'), ('dark', 'Dark theme')], max_length=50, null=True, verbose_name='Custom theme')),
                ('default_language_code', models.CharField(default='en', max_length=50, verbose_name='Default language code')),
                ('custom_language_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Custom language code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User settings',
                'verbose_name_plural': 'User settings',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', '-created_at'], name='auth_user_is_acti_6cfd8b_idx'),
        ),
        migrations.AddIndex(
            model_name='userdeliverydata',
            index=models.Index(fields=['is_active', '-created_at'], name='users_userd_is_acti_3c1760_idx'),
        ),
        migrations.AddIndex(
            model_name='userdeliverydata',
            index=models.Index(fields=['is_current'], name='idx_is_current'),
        ),
        migrations.AddConstraint(
            model_name='userdeliverydata',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('user',), name='unique_current_child_per_parent'),
        ),
        migrations.AddIndex(
            model_name='userpromocode',
            index=models.Index(fields=['is_active', '-created_at'], name='users_userp_is_acti_97139b_idx'),
        ),
        migrations.AddIndex(
            model_name='usersettingsdata',
            index=models.Index(fields=['is_active', '-created_at'], name='users_users_is_acti_6a5d43_idx'),
        ),
    ]
