# Generated by Django 5.2.17 on 2026-09-12 02:35

import apps.orders.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload_url', models.URLField(blank=True, null=True, verbose_name='Payload URL')),
                ('state', models.CharField(choices=[('pending', 'Waiting payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed', 'Failed (Needs review)')], default='pending', max_length=20, verbose_name='State')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount USD')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid at')),
                ('task_id', models.UUIDField(blank=True, null=True, verbose_name='Task ID')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('fixed_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fixed price')),
                ('is_digital', models.BooleanField(default=False, verbose_name='Is digital')),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order items',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('valid_from', models.DateTimeField(auto_now_add=True, verbose_name='Valid from')),
                ('valid_to', models.DateTimeField(default=apps.orders.models.get_default_promo_expiration, verbose_name='Valid to')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Min order amount')),
                ('work_for_everything', models.BooleanField(default=False, verbose_name='Work for everything')),
                ('discount_type', models.CharField(choices=[('amount', 'Fixed amount'), ('percent', 'Fixed percent')], default='percent', max_length=20, verbose_name='Discount type')),
                ('discount_percent', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Discount percent')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount amount')),
                ('max_uses', models.PositiveIntegerField(default=100, verbose_name='Max uses')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Used count')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, verbose_name='Max uses per user')),
            ],
            options={
                'verbose_name': 'Promo code',
                'verbose_name_plural': 'Promo codes',
                'abstract': False,
            },
        ),
    ]
