# Generated by Django 5.2.17 on 2026-09-12 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_history', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.productvariant', verbose_name='Variant'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='promocodes', to='catalog.category', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='promocodes', to='catalog.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='variants',
            field=models.ManyToManyField(blank=True, related_name='promocodes', to='catalog.productvariant', verbose_name='Variants'),
        ),
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.promocode', verbose_name='Promo code'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['is_active', '-created_at'], name='orders_orde_is_acti_eb0bde_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['is_active', '-created_at'], name='orders_prom_is_acti_d16a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_active', '-created_at'], name='orders_orde_is_acti_ffc494_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('state', 'pending')), fields=['state'], name='idx_pending_orders'),
        ),
    ]
