# Generated by Django 5.2.17 on 2026-09-12 02:35

import apps.core.storage
import django.core.validators
import uuid
from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
		TrigramExtension(),

        migrations.CreateModel(
            name='DigitalAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255, verbose_name='Content')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
            ],
            options={
                'verbose_name': 'Digital Asset',
                'verbose_name_plural': 'Digital Assets',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Favorite Item',
                'verbose_name_plural': 'Favorite Items',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('image', models.ImageField(storage=apps.core.storage.HashedStorage(), upload_to='products/gallery/', verbose_name='Image')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Ordering')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['ordering', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('product_type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('DIGITAL', 'Digital')], default='PHYSICAL', max_length=20, verbose_name='Product Type')),
                ('main_image', models.ImageField(blank=True, null=True, storage=apps.core.storage.HashedStorage(), upload_to='products/main/', verbose_name='Main Image')),
                ('video_file', models.FileField(blank=True, null=True, storage=apps.core.storage.HashedStorage(), upload_to='products/videos/', verbose_name='Video File')),
                ('video_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Video URL')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='Attributes')),
                ('base_description', models.TextField(blank=True, null=True, verbose_name='Base Description')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('badge', models.CharField(blank=True, max_length=50, null=True, verbose_name='Badge')),
                ('image', models.ImageField(blank=True, null=True, storage=apps.core.storage.HashedStorage(), upload_to='products/variants/', verbose_name='Image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Old Price')),
                ('discount_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Discount Expires At')),
                ('available_stock', models.IntegerField(default=0, verbose_name='Available Stock')),
                ('reserved_stock', models.IntegerField(default=0, verbose_name='Reserved Stock')),
                ('specific_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Specific Description')),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Weight (kg)')),
                ('length_cm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Length (cm)')),
                ('width_cm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Width (cm)')),
                ('height_cm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Height (cm)')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Task ID')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Universal field', null=True, verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Is Anonymous')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('admin_reply_text', models.TextField(blank=True, null=True, verbose_name='Admin Reply Text')),
                ('admin_reply_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Admin Reply Created At')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('image', models.ImageField(storage=apps.core.storage.HashedStorage(), upload_to='reviews/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Review Photo',
                'verbose_name_plural': 'Review Photos',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('name', models.CharField(verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('name', models.CharField(verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='catalog_cat_is_acti_3d8e37_idx')],
            },
        ),
    ]
