# Generated by Django 5.2.17 on 2026-09-12 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='photo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='catalog.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='digitalasset',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_assets', to='catalog.productvariant', verbose_name='Variant'),
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='reviewphoto',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.review', verbose_name='Review'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['is_active', '-created_at'], name='catalog_tag_is_acti_11a8c4_idx'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='variants', to='catalog.tag', verbose_name='Tags'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-created_at'], name='catalog_pro_is_acti_ed6a39_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['is_active', '-created_at'], name='catalog_pho_is_acti_5e8e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='favoriteitem',
            index=models.Index(fields=['is_active', '-created_at'], name='catalog_fav_is_acti_033ac1_idx'),
        ),
        migrations.AddConstraint(
            model_name='favoriteitem',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_favorite_item'),
        ),
        migrations.AddIndex(
            model_name='digitalasset',
            index=models.Index(fields=['is_active', '-created_at'], name='catalog_dig_is_acti_9bfc5e_idx'),
        ),
        migrations.AddConstraint(
            model_name='digitalasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_used', True), ('order_item__isnull', False)), models.Q(('is_used', False), ('order_item__isnull', True)), _connector='OR'), name='used_asset_must_have_order_item'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_active', '-created_at'], name='catalog_rev_is_acti_12d02e_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_review_per_user_product'),
        ),
        migrations.AddIndex(
            model_name='reviewphoto',
            index=models.Index(fields=['is_active', '-created_at'], name='catalog_rev_is_acti_7dd95d_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['is_active', '-created_at'], name='catalog_pro_is_acti_a0c862_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('available_stock__gte', 0)), name='available_stock_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_stock__gte', 0)), name='reserved_stock_not_negative'),
        ),
    ]
