# Generated by Django 5.2.17 on 2026-09-12 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order', verbose_name='Order'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['is_active', '-created_at'], name='delivery_de_is_acti_f4adc3_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(condition=models.Q(('state', 'pending')), fields=['state', 'provider_code'], name='pending_provider_code_delivery'),
        ),
    ]
