# Generated by Django 5.2.17 on 2026-09-12 02:35

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice ID')),
                ('payment_currency', models.CharField(max_length=10, verbose_name='Payment currency')),
                ('network', models.CharField(max_length=50, verbose_name='Network')),
                ('target_amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Target amount USD')),
                ('amount_crypto', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0E-8'))], verbose_name='Target crypto amount')),
                ('current_amount_crypto', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0E-8'))], verbose_name='Current crypto amount')),
                ('receiver_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Receiver address')),
                ('sender_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Sender address')),
                ('tx_hash', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction hash')),
                ('state', models.CharField(choices=[('pending', 'Waiting for payment'), ('paid', 'Successfully paid'), ('wrong_amount', 'Paid wrong amount'), ('partially_paid', 'Partially paid'), ('expired', 'Invoice expired'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='State')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='Raw gateway response')),
                ('task_id', models.UUIDField(blank=True, null=True, verbose_name='Task ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Payment transaction',
                'verbose_name_plural': 'Payment transactions',
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='payments_pa_is_acti_6c87b7_idx'), models.Index(condition=models.Q(('state__in', ['paid', 'expired', 'cancelled']), _negated=True), fields=['state'], name='idx_active_transactions')],
            },
        ),
    ]
