# Generated by Django 5.2.17 on 2026-09-12 02:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='State')),
                ('category', models.CharField(choices=[('bug', 'Bug Report'), ('order_issue', 'Order Issue'), ('general', 'General Question')], default='general', max_length=20, verbose_name='Category')),
                ('forum_topic_id', models.BigIntegerField(blank=True, null=True, verbose_name='Forum Topic ID')),
                ('triage_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Triage Message ID')),
                ('first_copy_triage_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='First Copy Triage Message ID')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_is_admin', models.BooleanField(default=False, verbose_name='Sender is Admin')),
                ('text', models.TextField(verbose_name='Text')),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram Message ID')),
            ],
            options={
                'verbose_name': 'Ticket Message',
                'verbose_name_plural': 'Ticket Messages',
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
