# Generated by Django 5.2.17 on 2026-09-12 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.ticket', verbose_name='Ticket'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['is_active', '-created_at'], name='support_tic_is_acti_8e3ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['is_active', '-created_at'], name='support_tic_is_acti_f43d69_idx'),
        ),
    ]
